### ISSUE TITLE
`request.auth` is a DRF specific attribute and is not compatible with Django

### ISSUE THREAD

**Issue by SamDudley** [uktrade/django-hawk#4]
https://github.com/uktrade/django-hawk/blob/35cae54654ee77bb2a78d514e55ef2205272b700/django_hawk/middleware.py#L18

Suggestion: Use the `mohawk.Receiver.respond` method to construct the `Server-Authorization` header.

**Comment by jafacakes2011** [comment]
Solved in https://github.com/uktrade/django-hawk/pull/6
