### ISSUE TITLE
Only apply the `Server-Authorization` header to `Hawk` requests

### ISSUE THREAD

**Issue by SamDudley** [uktrade/django-hawk#5]
https://github.com/uktrade/django-hawk/blob/35cae54654ee77bb2a78d514e55ef2205272b700/django_hawk/middleware.py#L18

Suggestion: Modify `authenticate_request` to add the `hawk_auth` attribute to the `request` object. This attribute can then be checked by the middleware to see if the request used Hawk authentication and needs the required header adding to the response.

**Comment by jafacakes2011** [comment]
Solved in https://github.com/uktrade/django-hawk/pull/6
